### ISSUE TITLE
How can I use Vexera's logo generator?

### ISSUE THREAD

**Issue by cobrexus** [SilverCory/VexeraLogoMeme#13]
Can I use Vexera's logo generator to create a non-copyright, no-attribution logo for my Discord servers and dev projects?

**Comment by SilverCory** [comment]
@itslukej ?

**Comment by RhvsW** [comment]
Install gentoo

**Comment by cobrexus** [comment]
> Install Gentoo

What does that mean?

**Comment by SilverCory** [comment]
That's Rhys being a cretin ---- On Sun, 24 May 2020 12:26:00 +0100  notifications@github.com  wrote ----

Install Gentoo

What does that mean?

**Comment by RhvsW** [comment]
> > Install Gentoo
> 
> What does that mean?

Install gentoo

**Comment by RhvsW** [comment]
Install gentoo

**Comment by RhvsW** [comment]
Install gentoo

**Comment by RhvsW** [comment]
Install gentoo

**Comment by RhvsW** [comment]
Install gentoo

**Comment by RhvsW** [comment]
Install gentoo

**Comment by lordjbs** [comment]
Install gentoo

**Comment by DoNotSpamPls** [comment]
install gentoo
